### ISSUE TITLE
Most of the hacks dont work

### ISSUE THREAD

**Issue by yapgamer** [rxzyx/Blooket-Hacks#153]
Im using firefox. The only one that works so far is the add token, the others such as select any blook dont work, I tested if they worked as a bookmarklet and the token one is the only one that works

I run the select any blook hack and this happens "Uncaught TypeError: Object.values(...).find(...) is undefined
    <anonymous> debugger eval code:1

Also how does the host folder stuff work?

**Comment by ZackiBoiz** [comment]
1. [Select any Blook.js](https://github.com/rxzyx/Blooket-Hacks/blob/main/Default%20Scripts/Select%20Any%20Blook.js) is being fixed - #148 
2. If you need to convert the scripts to bookmarklets, use [this](https://caiorss.github.io/bookmarklet-maker/)
3. I'm assuming you are talking about [this](https://github.com/rxzyx/Blooket-Hacks/tree/main/Default%20Scripts/Host) folder? If so, these hacks are ran by the host of the Blooket game. They allow easy control over the players, and the game. (Rather than manually removing every single player, one-by-one.)

**Comment by rxzyx** [comment]
^. Hacks work fine.
